version: "3.10.6"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      ADMIN: $ADMIN
      FORCE_SUB: $FORCE_SUB
      LOG_CHANNEL: $LOG_CHANNEL
      DB_URL: $DB_URL
